name: Daily Poll

on:
  schedule:
    - cron: '0 19 * * *'
  workflow_dispatch:

jobs:
  send_poll:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps
        run: pip install requests aiogram apscheduler python-dotenv
      - name: Run send_poll
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          GROUP: ${{ secrets.GROUP }}
        run: python3 setup_config_and_run.py
